import os

API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")

# Colors
BG = "#F8F9FA"
SURFACE = "#FFFFFF"
BORDER = "#E5E7EB"
TEXT_PRIMARY = "#111827"
TEXT_SECONDARY = "#6B7280"
ACCENT = "#1D4ED8"
ACCENT_LIGHT = "#EFF6FF"
SUCCESS = "#16A34A"
WARNING = "#D97706"
DANGER = "#DC2626"
DANGER_LIGHT = "#FEF2F2"

# Font families
FONT_FAMILY = "Segoe UI"
FONT_MONO = "Cascadia Code"
